idf_component_register(
    SRCS
        "main.cpp"
        "ch422g.cpp"
        "display.cpp"
        "touch.cpp"
        "ui.cpp"
        "screens/home.cpp"
    INCLUDE_DIRS "."
    REQUIRES
        esp_driver_i2c
        esp_mm
        esp_lcd
        esp_lcd_touch
        esp_lcd_touch_gt911
        esp_lvgl_adapter
        esp_timer
        driver
        freertos
        log
)
