// usb_midi_driver.cpp — TinyUSB MIDI 1.0 Class Device driver
//
// ESP32-S3 native USB OTG: GPIO19 = D-,  GPIO20 = D+
// TinyUSB component:       esp-idf-5.5/components/tinyusb
//
// Descriptor layout (auto-generated by ESP-IDF TinyUSB wrapper):
//   - 1 MIDI IN  jack  (embedded)  — USB → device
//   - 1 MIDI OUT jack  (embedded)  — device → USB
//
// Threading: tinyusb_driver_install() spawns its own tud_task() FreeRTOS
// task internally (controlled by CONFIG_TINYUSB_TASK_PRIORITY /
// CONFIG_TINYUSB_TASK_STACK_SIZE).  We do NOT start a second task.
// usb_midi_send_cc() is safe from any task via the TinyUSB endpoint FIFO.

#include "usb_midi_driver.h"

#include "tinyusb.h"
#include "class/midi/midi_device.h"

#include "esp_log.h"

static const char *TAG = "usb_midi";

// ── Public API ────────────────────────────────────────────────────────────────

void usb_midi_driver_init()
{
    ESP_LOGI(TAG, "Initialising TinyUSB MIDI device");

    // tinyusb_config_t uses sensible defaults for ESP32-S3 (full-speed OTG).
    // All descriptor fields (VID/PID/strings) come from sdkconfig / Kconfig.
    // The ESP-IDF wrapper builds the MIDI class descriptor automatically when
    // CONFIG_TINYUSB_MIDI_ENABLED=y; we do not need to supply one manually.
    const tinyusb_config_t tusb_cfg = {
        .device_descriptor        = nullptr, // use auto-generated descriptor
        .string_descriptor        = nullptr,
        .string_descriptor_count  = 0,
        .external_phy             = false,   // internal PHY (GPIO19/20)
        .configuration_descriptor = nullptr, // auto-generated (MIDI class)
        .self_powered             = false,
        .vbus_monitor_io          = -1,      // no VBUS monitoring GPIO
    };

    ESP_ERROR_CHECK(tinyusb_driver_install(&tusb_cfg));
    // tinyusb_driver_install() spawns the tud_task() background thread.

    ESP_LOGI(TAG, "TinyUSB MIDI device ready (GPIO19=D- GPIO20=D+)");
}

void usb_midi_send_cc(uint8_t channel, uint8_t cc, uint8_t value)
{
    if (!tud_midi_mounted()) {
        // Host not connected or device not enumerated yet — silently drop
        ESP_LOGD(TAG, "MIDI not mounted — CC %u val %u dropped", cc, value);
        return;
    }

    // MIDI 1.0 Control Change: status byte = 0xB0 | channel
    const uint8_t msg[3] = {
        static_cast<uint8_t>(0xB0u | (channel & 0x0Fu)),
        static_cast<uint8_t>(cc    & 0x7Fu),
        static_cast<uint8_t>(value & 0x7Fu),
    };

    // tud_midi_stream_write wraps the 3-byte message in USB-MIDI packets
    // and writes to the endpoint FIFO. Thread-safe internally.
    const uint32_t written = tud_midi_stream_write(0, msg, sizeof(msg));
    if (written != sizeof(msg)) {
        ESP_LOGW(TAG, "MIDI FIFO full — CC %u dropped (%lu/%u bytes written)",
                 cc, written, (unsigned)sizeof(msg));
    } else {
        ESP_LOGD(TAG, "CC ch=%u cc=%u val=%u sent", channel, cc, value);
    }
}
